"""add data_nascimento to clients

Revision ID: 420fee598110
Revises: 20250818_0001
Create Date: 2025-09-11 00:11:00.737591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420fee598110'
down_revision = '20250818_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Adiciona a coluna como nullable e com valor default
    op.add_column('clients', sa.Column('data_nascimento', sa.DateTime(), nullable=True))
    # Atualiza os registros existentes para o valor default
    op.execute("UPDATE clients SET data_nascimento = '1900-01-01' WHERE data_nascimento IS NULL")
    # Altera a coluna para NOT NULL
    op.alter_column('clients', 'data_nascimento', nullable=False)
    op.drop_index(op.f('ix_clients_cpf'), table_name='clients')
    op.create_index(op.f('ix_clients_data_nascimento'), 'clients', ['data_nascimento'], unique=False)
    op.drop_column('clients', 'cpf')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('cpf', sa.VARCHAR(length=14), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_clients_data_nascimento'), table_name='clients')
    op.create_index(op.f('ix_clients_cpf'), 'clients', ['cpf'], unique=True)
    op.drop_column('clients', 'data_nascimento')
    # ### end Alembic commands ###